import fs from 'node:fs/promises';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';

const root = process.cwd();
const csv = await fs.readFile(`${root}/peptide_protocol_database_excel.csv`, 'utf8');
const rows = csv.trim().split(/\r?\n/).slice(1).map(line => {
  const out=[]; let v='', q=false;
  for (let i=0;i<line.length;i++) { const c=line[i]; if(c==='"') { if(q&&line[i+1]==='"'){v+='"';i++;} else q=!q; } else if(c===','&&!q){out.push(v);v='';} else v+=c; }
  out.push(v); return {peptide:out[0],range:out[1],cycle:out[2],url:out[3]};
});
const clean = s => s.replace(/\[[^\]]+\]/g,'').replace(/\s+/g,' ').trim();
const goal = {
  '5-Amino-1MQ':'Metabolic efficiency and fat oxidation research','Adamax':'Cognitive enhancement and neuroplasticity research','Adipotide':'Fat-mass reduction research','AICAR':'AMPK activation and metabolic research','AOD-9604':'Fat oxidation research','Ara-290':'Tissue protection and anti-inflammatory research','BPC-157':'Tissue-healing and recovery research','Cagrilintide':'Satiety and weight-management research','CJC-1295 DAC':'Endogenous GH and IGF-1 research','CJC-1295 NO DAC':'Pulsatile GH release research','DSIP':'Sleep and stress-modulation research','Epitalon (Epithalon)':'Telomere and melatonin research','GHK-Cu':'GHK-Cu protocol and measurement research','Glutathione':'Antioxidant and detoxification research','HCG':'Testicular function and fertility research','HMG':'Spermatogenesis research','MOTS-C':'Metabolic homeostasis and insulin-sensitivity research','NAD+':'Cellular energy and mitochondrial research','PT-141':'Sexual desire and arousal research','Retatrutide':'Weight-reduction and metabolic research','Semaglutide':'Chronic weight-management research','SS-31':'Mitochondrial function research','TB-500':'Tissue repair and angiogenesis research','Tesamorelin':'Visceral-fat and lipid-profile research','Thymosin Alpha-1':'Immune-modulation research','Tirzepatide':'Glycemic control and weight-management research'
};
function method(range, peptide) { if (/intranasal/i.test(range)) return 'Intranasal'; if (/topical/i.test(range)||peptide==='SNAP-8') return 'Topical'; if (/mouse|murine/i.test(range)) return 'Animal research (intraperitoneal)'; return 'Subcutaneous injection'; }
function nums(range) { const weekly=/weekly|per week|× weekly|3×/i.test(range); const pair=range.match(/(\d[\d,.]*)\s*[–-]\s*(\d[\d,.]*)\s*(mcg|µg|mg|IU|%)/i); const matches=[...range.matchAll(/(\d[\d,.]*)(?:\s*)(mcg|µg|mg|IU|%)/gi)].map(m=>`${m[1]} ${m[2]}`); const low=pair?`${pair[1]} ${pair[3]}`:(matches[0]||'Not stated'); const high=pair?`${pair[2]} ${pair[3]}`:(matches[1]||matches[0]||'Not stated'); return {min:weekly?'N/A (weekly protocol)':low,max:weekly?'N/A (weekly protocol)':high,week:weekly?high:'Not stated'}; }
function timing(range, peptide) { const t=(range+' '+peptide).toLowerCase(); if(t.includes('bedtime')||t.includes('night')) return 'Evening / bedtime'; if(t.includes('morning')) return 'Morning'; return 'Not specified'; }
function cycleParts(c) { const s=clean(c); const on=(s.match(/^(\d+(?:–\d+)?\s*(?:days?|weeks?|months?)(?:\s+on)?)/i)||[])[1]||s; const off=(s.match(/(?:then|followed by|off(?:-cycle)?(?: period)? of?)\s+(\d+(?:–\d+)?\s*(?:days?|weeks?|months?)[^;,.]*)/i)||[])[1]||'Not stated'; return [on,off]; }
const normalized=rows.map(r=>{ const n=nums(r.range), c=cycleParts(r.cycle); return [r.peptide,method(r.range,r.peptide),n.min,n.max,n.week,timing(r.range,r.peptide),c[0],c[1],goal[r.peptide]||'See linked protocol page',r.url]; });
const blendRows=[
['AOD-9604 + CJC-1295 + Ipamorelin (12 mg Blend)','Subcutaneous injection','200/100/100 mcg (AOD/CJC/Ip)','400/200/200 mcg (AOD/CJC/Ip)','Not stated','Morning or before bed; empty stomach','8–16 weeks','Not stated','Body-composition research','https://peptidedosages.com/peptide-blend-dosages/aod-9604-cjc-1295-ipamorelin-12-mg-blend-dosage-protocol/'],
['BPC-157 + TB-500 (10 mg Blend)','Subcutaneous injection','600 mcg total','1,000 mcg total','Not stated','Not specified','8 weeks','Not stated','Tissue repair research','https://peptidedosages.com/peptide-blend-dosages/bpc-157-tb-500-10mg-blend-dosage-protocol/'],
['BPC-157 + TB-500 (20 mg Blend)','Subcutaneous injection','500 mcg total','1,000 mcg total','Not stated','Not specified','4–8 weeks','Not stated','Tissue repair research','https://peptidedosages.com/peptide-blend-dosages/bpc-157-tb-500-20mg-blend-dosage-protocol/'],
['Cagrilintide + Semaglutide (10 mg Blend)','Subcutaneous injection','N/A (weekly)','N/A (weekly)','2.4 mg of each peptide weekly','Not specified','16+ weeks','Not stated','Satiety and weight-management research','https://peptidedosages.com/peptide-blend-dosages/cagrilintide-semaglutide-10-mg-blend-dosage-protocol/'],
['CJC-1295 + GHRP-2 (10 mg Blend)','Subcutaneous injection','100 mcg','300 mcg','Not stated','Timing tied to research design','8–16 weeks','Not stated','Growth-hormone release research','https://peptidedosages.com/peptide-blend-dosages/cjc-1295-ghrp-2-10mg-blend-dosage-protocol/'],
['CJC-1295 NO DAC + Ipamorelin (10 mg Blend)','Subcutaneous injection','100 mcg each','300 mcg each','Not stated','Bedtime preferred','8–16 weeks','Not stated','Growth-hormone release research','https://peptidedosages.com/peptide-blend-dosages/cjc-1295-no-dac-ipamorelin-10-mg-blend-dosage-protocol/'],
['GLOW (70 mg Blend)','Subcutaneous injection','2.33 mg total','2.33 mg total','Not stated','Not specified','4 weeks','2–4 weeks','Tissue-healing research','https://peptidedosages.com/peptide-blend-dosages/glow-peptide-blend-70-mg-vial-dosage-protocol/'],
['KLOW (80 mg Blend)','Subcutaneous injection','250 mcg each; 1.25 mg GHK-Cu','750 mcg each; 3.75 mg GHK-Cu','Not stated','Not specified','8–16 weeks','Not stated','Regenerative and anti-inflammatory research','https://peptidedosages.com/peptide-blend-dosages/klow-80-mg-vial-dosage-protocol/'],
['Neuroxelin (48 mg Vial)','Subcutaneous injection','250 mcg','1,000 mcg','Not stated','Morning preferred','8–12 weeks','Not stated','Neuroprotection and cognitive-recovery research','https://peptidedosages.com/peptide-blend-dosages/neuroxelin-48-mg-vial-dosage-protocol/'],
['Tesamorelin + Ipamorelin (10 mg Blend)','Subcutaneous injection','250 mcg tesamorelin + 125 mcg ipamorelin','2,000 mcg tesamorelin + 1,000 mcg ipamorelin','Not stated','Night','8–16 weeks','Not stated','Growth-hormone pulse research','https://peptidedosages.com/peptide-blend-dosages/tesamorelin-5-mg-ipamorelin-5-mg-10-mg-blend-dosage-protocol/'],
['Tri-Heal (45 mg Blend)','Subcutaneous injection','500 mcg total','4,000 mcg total (extended)','Not stated','Not specified','8–16 weeks','Not stated','Tissue repair and inflammation-modulation research','https://peptidedosages.com/peptide-blend-dosages/tri-heal-tb-500-25-mg-bpc-157-10-mg-kpv-10-mg-vial-dosage-protocol/']];
normalized.push(...blendRows);
const wb=Workbook.create();
const main=wb.worksheets.add('Protocol Database'); const raw=wb.worksheets.add('Source Data'); const notes=wb.worksheets.add('Read Me');
const headers=['Peptide name','Method','Minimum daily recommended dose','Maximum daily recommended dose','Maximum weekly recommended dose','Time of day for dosing','Cycle length on','Cycle length off','Goal','Link to page'];
main.getRange(`A1:J${normalized.length+1}`).values=[headers,...normalized];
raw.getRange(`A1:D${rows.length+blendRows.length+1}`).values=[['Peptide name','Site-stated range','Site-stated cycle guidance','Source URL'],...rows.map(r=>[r.peptide,r.range,r.cycle,r.url]),...blendRows.map(r=>[r[0],`${r[2]} to ${r[3]}`,`On: ${r[6]}; Off: ${r[7]}`,r[9]])];
notes.getRange('A1:B8').values=[['Peptide Protocol Workbook',''],['Purpose','Normalized reference from PeptideDosages.com protocol pages.'],['Dose fields','Values retain source units; weekly, topical, intranasal and animal-only protocols are not converted to daily human doses.'],['Cycle fields','On/off values are separated when the source explicitly provides them.'],['Goal','A concise research-purpose summary; check each linked page for full context.'],['Source date','2026-07-18'],['Safety note','Research reference only; not medical advice.'],['Source index','https://peptidedosages.com/single-peptide-dosages/']];
for (const sh of [main,raw,notes]) { sh.showGridLines=false; sh.freezePanes.freezeRows(1); }
for (const sh of [main,raw]) { const used=sh.getUsedRange(); used.format.wrapText=true; used.format.font={name:'Aptos',size:10}; sh.getRange(`A1:${sh===main?'J':'D'}1`).format={fill:'#0F766E',font:{bold:true,color:'#FFFFFF',size:10},horizontalAlignment:'center',verticalAlignment:'center'}; used.format.borders={preset:'inside',style:'thin',color:'#D9E2E7'}; }
main.getRange(`A2:J${normalized.length+1}`).format.rowHeight=34; main.getRange('A:A').format.columnWidth=21; main.getRange('B:B').format.columnWidth=22; main.getRange('C:E').format.columnWidth=22; main.getRange('F:H').format.columnWidth=20; main.getRange('I:I').format.columnWidth=36; main.getRange('J:J').format.columnWidth=48;
raw.getRange('A:A').format.columnWidth=22; raw.getRange('B:C').format.columnWidth=46; raw.getRange('D:D').format.columnWidth=52; raw.getRange(`A2:D${rows.length+blendRows.length+1}`).format.rowHeight=30;
notes.getRange('A1:B1').format={fill:'#0F766E',font:{bold:true,color:'#FFFFFF',size:14}}; notes.getRange('A1:B8').format.wrapText=true; notes.getRange('A:A').format.columnWidth=20; notes.getRange('B:B').format.columnWidth=100; notes.getRange('A2:A8').format.font={bold:true,color:'#0F766E'};
await fs.mkdir(`${root}/outputs/protocol_workbook`,{recursive:true}); const x=await SpreadsheetFile.exportXlsx(wb); await x.save(`${root}/outputs/protocol_workbook/peptide_protocol_database.xlsx`);
